name: Build, tag, and release the BreezSDK Swift Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release of the breez-sdk repo to publish (MAJOR.MINOR.PATCH)'
        required: true
        type: string

jobs:
  build-tag-release:
    name: Build, tag, and release the BreezSDK Swift Package
    runs-on: macos-12
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/breez-sdk
          path: build
          # ref: v${{ inputs.version }}
      - name: Checkout breez-sdk-swift repo
        uses: actions/checkout@v3
        with:
          path: dist
